### PR TITLE
bumped analyzer version to 4.0.0 and fixed tests

### PR DESCRIPTION
**Pull request by michaelgobbers**

### CODE REVIEW

**Comment by acoutts** [comment]
@aboo @doppio @refi64 @fryette any chance for a review for this one to silence the warning in flutter 3.0 (stable)?

**Comment by leoshusar** [comment]
@Milad-Akarie could you please look at this soon? Thank you!

**Comment by camillobucciarelli** [comment]
Is it any news about this PR?

**Comment by dJani97** [comment]
Would love to see this merged.

I'm unable to use the latest versions of other packages because `injectable_generator: ^1.5.3` still depends on Analyzer 3.

**Comment by icodelifee** [comment]
> Would love to see this merged.
> 
> I'm unable to use the latest versions of other packages because `injectable_generator: ^1.5.3` still depends on Analyzer 3.

only way until this gets merged or the author updates the package is to use the pr repo

```
  injectable_generator:
    git:
      url: https://github.com/michaelgobbers/injectable.git/
      ref: master
      path: injectable_generator
```

**Pull request merged**
