### PR TITLE
upgrading pub packages

### PR DESCRIPTION
**Pull request by kzawadi**
fixing issues with other packages depending on analyzer version 5.0.0 #304

### CODE REVIEW

**Comment by arifikhsan** [comment]
looking forward for this analyzer version update

**Comment by guyluz11** [comment]
I have tested your fork and I think I am getting errors when using 

`flutter pub run build_runner watch --delete-conflicting-outputs --use-polling-watcher`

**Comment by kzawadi** [comment]
Can you post the errors you have gotten

**Comment by guyluz11** [comment]
Using your branch as follows in pubspec.yaml
```
injectable_generator:
  git:
    ref: patch-1
    url: https://github.com/kzawadi/injectable
    path: injectable_generator
```

Running this commends in the terminal
flutter pub get

`flutter clean` `flutter pub cache repair` `flutter pub get` `flutter pub run build_runner clean`

`flutter pub run build_runner watch --delete-conflicting-outputs --use-polling-watcher`

I am getting this error when trying to generate files


```dart
$ flutter pub run build_runner watch --delete-conflicting-outputs --use-polling-watcher
[INFO] Generating build script...
[INFO] Generating build script completed, took 289ms

[INFO] Precompiling build script......
[WARNING] ../../../snap/flutter/common/flutter/.pub-cache/git/injectable-efc5ce0d86fd6d747c2071c8059411231b8caf09/injectable_generator/lib/resolvers/importable_type_resolver.dart:77:35: Error: The getter 'element' isn't defined for the class 'FunctionType'.
 - 'FunctionType' is from 'package:analyzer/dart/element/type.dart' ('../../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/analyzer-5.1.0/lib/dart/element/type.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'element'.
        executableElement ?? type.element ?? type.alias?.element;
                                  ^^^^^^^
../../../snap/flutter/common/flutter/.pub-cache/git/injectable-efc5ce0d86fd6d747c2071c8059411231b8caf09/injectable_generator/lib/resolvers/importable_type_resolver.dart:103:18: Error: The getter 'element' isn't defined for the class 'DartType'.
 - 'DartType' is from 'package:analyzer/dart/element/type.dart' ('../../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/analyzer-5.1.0/lib/dart/element/type.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'element'.
        if (type.element is TypeParameterElement) {
                 ^^^^^^^
../../../snap/flutter/common/flutter/.pub-cache/git/injectable-efc5ce0d86fd6d747c2071c8059411231b8caf09/injectable_generator/lib/resolvers/importable_type_resolver.dart:107:24: Error: The getter 'element' isn't defined for the class 'DartType'.
 - 'DartType' is from 'package:analyzer/dart/element/type.dart' ('../../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/analyzer-5.1.0/lib/dart/element/type.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'element'.
            name: type.element?.name ??
                       ^^^^^^^
../../../snap/flutter/common/flutter/.pub-cache/git/injectable-efc5ce0d86fd6d747c2071c8059411231b8caf09/injectable_generator/lib/resolvers/importable_type_resolver.dart:109:40: Error: The getter 'element' isn't defined for the class 'DartType'.
 - 'DartType' is from 'package:analyzer/dart/element/type.dart' ('../../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/analyzer-5.1.0/lib/dart/element/type.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'element'.
            import: resolveImport(type.element),
                                       ^^^^^^^
../../../snap/flutter/common/flutter/.pub-cache/git/injectable-efc5ce0d86fd6d747c2071c8059411231b8caf09/injectable_generator/lib/resolvers/importable_type_resolver.dart:122:18: Error: The getter 'element' isn't defined for the class 'DartType'.
 - 'DartType' is from 'package:analyzer/dart/element/type.dart' ('../../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/analyzer-5.1.0/lib/dart/element/type.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'element'.
      name: type.element?.name ?? type.getDisplayString(withNullability: false),
                 ^^^^^^^
../../../snap/flutter/common/flutter/.pub-cache/git/injectable-efc5ce0d86fd6d747c2071c8059411231b8caf09/injectable_generator/lib/resolvers/importable_type_resolver.dart:124:34: Error: The getter 'element' isn't defined for the class 'DartType'.
 - 'DartType' is from 'package:analyzer/dart/element/type.dart' ('../../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/analyzer-5.1.0/lib/dart/element/type.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'element'.
      import: resolveImport(type.element),
                                 ^^^^^^^
../../../snap/flutter/common/flutter/.pub-cache/git/injectable-efc5ce0d86fd6d747c2071c8059411231b8caf09/injectable_generator/lib/resolvers/dependency_resolver.dart:60:18: Error: The getter 'element' isn't defined for the class 'DartType'.
 - 'DartType' is from 'package:analyzer/dart/element/type.dart' ('../../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/analyzer-5.1.0/lib/dart/element/type.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'element'.
      returnType.element is! ClassElement,
                 ^^^^^^^
../../../snap/flutter/common/flutter/.pub-cache/git/injectable-efc5ce0d86fd6d747c2071c8059411231b8caf09/injectable_generator/lib/resolvers/dependency_resolver.dart:62:27: Error: The getter 'element' isn't defined for the class 'DartType'.
 - 'DartType' is from 'package:analyzer/dart/element/type.dart' ('../../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/analyzer-5.1.0/lib/dart/element/type.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'element'.
      element: returnType.element,
                          ^^^^^^^
../../../snap/flutter/common/flutter/.pub-cache/git/injectable-efc5ce0d86fd6d747c2071c8059411231b8caf09/injectable_generator/lib/resolvers/dependency_resolver.dart:68:26: Error: The getter 'element' isn't defined for the class 'DartType'.
 - 'DartType' is from 'package:analyzer/dart/element/type.dart' ('../../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/analyzer-5.1.0/lib/dart/element/type.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'element'.
      clazz = returnType.element;
                         ^^^^^^^
../../../snap/flutter/common/flutter/.pub-cache/git/injectable-efc5ce0d86fd6d747c2071c8059411231b8caf09/injectable_generator/lib/resolvers/dependency_resolver.dart:78:45: Error: The getter 'element' isn't defined for the class 'DartType'.
 - 'DartType' is from 'package:analyzer/dart/element/type.dart' ('../../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/analyzer-5.1.0/lib/dart/element/type.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'element'.
        clazz = typeArg.typeArguments.first.element;
                                            ^^^^^^^
../../../snap/flutter/common/flutter/.pub-cache/git/injectable-efc5ce0d86fd6d747c2071c8059411231b8caf09/injectable_generator/lib/resolvers/dependency_resolver.dart:81:28: Error: The getter 'element' isn't defined for the class 'DartType'.
 - 'DartType' is from 'package:analyzer/dart/element/type.dart' ('../../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/analyzer-5.1.0/lib/dart/element/type.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'element'.
        clazz = returnType.element;
                           ^^^^^^^
../../../snap/flutter/common/flutter/.pub-cache/git/injectable-efc5ce0d86fd6d747c2071c8059411231b8caf09/injectable_generator/lib/resolvers/dependency_resolver.dart:141:65: Error: The getter 'element' isn't defined for the class 'InterfaceType'.
 - 'InterfaceType' is from 'package:analyzer/dart/element/type.dart' ('../../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/analyzer-5.1.0/lib/dart/element/type.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'element'.
          .firstOrNull((type) => abstractChecker.isExactly(type.element));
                                                                ^^^^^^^
[INFO] Precompiling build script... completed, took 4.9s

[SEVERE] Failed to precompile build script .dart_tool/build/entrypoint/build.dart.
This is likely caused by a misconfigured builder definition.

pub finished with exit code 78
```

**Comment by Milad-Akarie** [comment]
Sorry for the delay, I merged the one with latest version constrains

**Pull request closed without merging**
