### PR TITLE
Migrate to analyzer 3.0.0

### LINKED ISSUE #263: not support with analyzer 3.0.0
https://github.com/dart-lang/build/issues/3226#issuecomment-1000607131

```
D:\dev\ideaProjects\WEB-MB-BackOffice>flutter pub run build_runner build --delete-conflicting-outputs
[INFO] Generating build script...
[INFO] Generating build script completed, took 806ms

[INFO] Precompiling build script......
[WARNING] /C:/Users/u066757/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/injectable_generator-1.5.2/lib/resolvers/importable_type_resolver.dart:77:51: Error: The getter 'aliasElement' isn't defined for the class 'FunctionType'.
 - 'FunctionType' is from 'package:analyzer/dart/element/type.dart' ('/C:/Users/u066757/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/analyzer-3.0.0/lib/dart/element/type.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'aliasElement'.
        executableElement ?? type.element ?? type.aliasElement;
                                                  ^^^^^^^^^^^^
[INFO] Precompiling build script... completed, took 9.5s

[SEVERE] Failed to precompile build script .dart_tool/build/entrypoint/build.dart.
This is likely caused by a misconfigured builder definition.

pub finished with exit code 78
```

### PR DESCRIPTION
**Pull request by proninyaroslav**
Fix  #263

### CODE REVIEW

**Review by FaKenKoala — COMMENTED** [review]
LGTM

**Comment by humbold2020** [comment]
oh please fix soon!

**Comment by proninyaroslav** [comment]
@humbold2020 
You can use my workaround https://github.com/Milad-Akarie/injectable/issues/263#issuecomment-1002952762

**Comment by humbold2020** [comment]
Thank you

**Pull request merged**
