### PR TITLE
Injectable null safety

### PR DESCRIPTION
**Pull request by britannio**
The first step towards addressing https://github.com/Milad-Akarie/injectable/issues/170 and https://github.com/Milad-Akarie/injectable/issues/147

I'm curious as to why this isn't split into two separate classes?
https://github.com/Milad-Akarie/injectable/blob/master/injectable/lib/src/injectable_annotations.dart#L98-L112

### CODE REVIEW

**Comment by britannio** [comment]
Migrating injectable_generator requires https://github.com/dart-lang/source_gen/issues/493 and https://github.com/dart-lang/build/issues/2920 (in progress: https://github.com/dart-lang/build/pull/2996)

**Comment by Milad-Akarie** [comment]
Hey @britannio  for some reason I didn't get notified about the this pull request. anyways I'm refactoring the code generator to use code_builder library before I put in work in migration as the current code is a bit messy.

**Comment by britannio** [comment]
Sounds good!

**Comment by Milad-Akarie** [comment]
@britannio It's already done, Thanks for your efforts.
nullsafety version was just released 
https://pub.dev/packages/injectable/versions/1.2.0-nullsafety
https://pub.dev/packages/injectable_generator/versions/1.2.0-nullsafety

**Pull request closed without merging**
