### PR TITLE
feat: add GetItHelper exporter for micro modules 

### PR DESCRIPTION
**Pull request by SalihCanBinboga**
Hello 👋, I have been using the Injectable package for a long time. While developing a multi-module project, I wanted to add a feature to address an issue I encountered. With this feature, sub-modules can access the getItHelper instances generated in the main module. Thank you.

Related issue: #381

### CODE REVIEW

**Comment by Milad-Akarie** [comment]
Hey, @SalihCanBinboga  what's the use case of this? also, could you share a generated code showing the result?

**Comment by SalihCanBinboga** [comment]
> Hey, @SalihCanBinboga what's the use case of this? also, could you share a generated code showing the result?

Hey @Milad-Akarie of course I can provide further information. I am preparing the content.

**Comment by SalihCanBinboga** [comment]
This is an example project: [Project](https://github.com/SalihCanBinboga/recipe_finder/tree/feature/improve-modularization)
You can see the generated code here: [Generated Code Snippet](https://github.com/SalihCanBinboga/recipe_finder/blob/feature/improve-modularization/modules/features/home/lib/home.module.dart#L15)
You can also see the usage here: [Usage](https://github.com/SalihCanBinboga/recipe_finder/blob/feature/improve-modularization/modules/features/home/lib/presentation/home_view.dart#L50)

With this structure, I am providing the top-level 'getit' instances to the sub-modules in a generic manner.


Also, this is generated 'InjectableInit' InjectableConfigGenerator result:

```dart
import 'package:core/utils/debounce_manager.dart' as _i8;
import 'package:data/data.module.dart' as _i3;
import 'package:domain/domain.module.dart' as _i4;
import 'package:favourite_recipes/favourite_recipes.module.dart' as _i7;
import 'package:get_it/get_it.dart' as _i1;
import 'package:home/home.module.dart' as _i5;
import 'package:injectable/injectable.dart' as _i2;
import 'package:recipe_detail/recipe_detail.module.dart' as _i6;

import 'modules/debounce_manager_module.dart' as _i9;

extension GetItInjectableX on _i1.GetIt {
  // initializes the registration of main-scope dependencies inside of GetIt
  Future<_i1.GetIt> startInjection({
    String? environment,
    _i2.EnvironmentFilter? environmentFilter,
  }) async {
    final gh = _i2.GetItHelper(
      this,
      environment,
      environmentFilter,
    );
    await _i3.DataPackageModule().init(gh);
    await _i4.DomainPackageModule().init(gh);
    await _i5.HomePackageModule().init(gh);
    await _i6.RecipeDetailPackageModule().init(gh);
    await _i7.FavouriteRecipesPackageModule().init(gh);
    final debounceManagerModule = _$DebounceManagerModule();
    gh.singleton<_i8.DebounceManager>(
        debounceManagerModule.createDebounceManager());
    return this;
  }
}

class _$DebounceManagerModule extends _i9.DebounceManagerModule {}

```

**Comment by SalihCanBinboga** [comment]
Hi @Milad-Akarie  👋 is everything okay? If you want, I can explain in more detail.

**Comment by Milad-Akarie** [comment]
Hey @SalihCanBinboga sorry for the late response, I had to think about this for a minute, wouldn't you think it's better if we register the `GetItHelper` in the main package as a singleton, then sub-packages can simply inject it to access it?

**Comment by SalihCanBinboga** [comment]
> Hey @SalihCanBinboga sorry for the late response, I had to think about this for a minute, wouldn't you think it's better if we register the `GetItHelper` in the main package as a singleton, then sub-packages can simply inject it to access it?

Hi 👋 @Milad-Akarie yes, what you are doing could be a solution, but according to SOLID and DDD principles, 'upper layers cannot be dependent on lower layers,' so this structure would not be correct. With this method, the relevant modules become able to access the related instance without being dependent on the upper layers.

**Comment by SalihCanBinboga** [comment]
Hello @Milad-Akarie , how are you? If you have any concerns about this approach, please let me know, and let's try to resolve them through discussion.

**Comment by Milad-Akarie** [comment]
Hey @SalihCanBinboga sorry for the delayed response, I'm honestly still thinking of a better way to do this as I don't like the idea of assigning a late variable because it can easily cause runtime errors if accessed before initialized. 

I don't think what I suggested (injecting the get_it helper instance ) by the main package is different from injecting it through the module and assigning it to a late var. 

what do you think?

**Comment by SalihCanBinboga** [comment]
I understand you @Milad-Akarie . In your first suggestion, if we define a package like 'core' instead of 'main package,' it won't pose any architectural problems as it will be defined with the lowest dependency. I've adapted the structure you mentioned to the relevant [project](https://github.com/SalihCanBinboga/recipe_finder/blob/master/modules/core/lib/di/di_container_provider.dart) and saw that it works smoothly. It seems right to me to proceed this way as well. 
Thank you.

**Pull request closed without merging**
