### PR TITLE
Change usage of 'Set' to 'List' to retain collection ordering

### LINKED ISSUE #404: Different dependency ordering with the same code
Running `flutter packages run build_runner build --delete-conflicting-outputs` can produce different imports and dependency ordering with the same code.
изображение
It's not a problem until you trying to use build_verify that fails if something changed.
```
Expected: empty
  Actual: 'diff --git a/lib/di/injectable.config.dart b/lib/di/injectable.config.dart\n'
```

injectable: 2.1.0
injectable_generator: 2.1.3
build_runner: 2.3.0
build_verify: 3.1.0
dart: 2.18.4
flutter: 3.3.8

Original issue https://github.com/Milad-Akarie/injectable/issues/337 , https://github.com/Milad-Akarie/injectable/issues/371

### PR DESCRIPTION
**Pull request by Adam-Langley**
Fixes #404 

Consecutive regenerations of get_it.config.dart without any change to the underlying dependency configuration, result in differing order of dependency registration - essentially unnecessary code churn that creates noise in source control, and potential source control conflicts.
Found 2 contributing factors:
1. During generation, dependences undergo a sequence of ordering steps, the first of which an alphabetical ordering - which needed to be expanded to key off more than just the type name - this has been expanded to 'toString' the dependency config - ensuring uniqueness across type name, parameters, environment, etc
2. subsequent ordering steps first convert the previously ordered list to a set (List.toSet https://api.dart.dev/stable/3.3.1/dart-core/Iterable/toSet.html) - essentially destroying the previously stored ordering

### CODE REVIEW

**Comment by Adam-Langley** [comment]
Hi @Milad-Akarie 
There are essentially 3 changes in this PR
1. During dependency ordering, I have extended the "alphabetical" ordering stage to utilise the DepedencyConfig.toString instead of ordering only by 'type.name' - to ensure that no 2 dependencies could be evaluated as "equivalent" - causing potential non-determinism
2. Subsequent ordering steps were converting the output of the previous stage from List to Set, using 'toSet'. I must admit I do not know why this was being done, but it does result in the loss of ordering produced by the previous step. I've hence changed the code to operate on Lists instead of Sets.
3. Updated the relevant unit tests which now need to pass Lists instead of Sets to these functions

**Comment by saschaernst** [comment]
You are my personal hero!

**Comment by saschaernst** [comment]
As this is also about preventing merge conflicts in bigger teams, I suspect a problem with the naming of the aliases for the imports (i.e. _i12, _i34, etc.). I guess adding one new injection would change the numbering without a problem, but when to branches add something, the merge could be conflicting again eventually.
Could the DepedencyConfig.toString be used to generate unique aliases independent of other added injections?

**Comment by Milad-Akarie** [comment]
Hey @Adam-Langley nice work as usual, can't we handle the alphabet order without using the toString() method? I just feel like it's not reliable enough, I just changed it a couple days ago to print the formatted Json of the instance so that I can effectively trace diffs outputted by tests, I also feel like it would be a bit expensive to compare by the whole instance's Json, I suggest using type.identity which is a combination of type's location and name, better yet, we could have a detected  unique identifier where we calculate the hash of every property that can make the `DependencyConfig` unique? 

```dart
  int get identityHash =>
      type.identity.hashCode ^
      typeImpl.identity.hashCode ^
      injectableType.hashCode ^
      const ListEquality<InjectedDependency>().hash(dependencies);
   /// other unique fields..

```
Your thoughts?

**Comment by Milad-Akarie** [comment]
@Adam-Langley ya, I or some other attributor may change the `toString()` implementation for any reason, I'm still not sure if using the hashing approach is more performant, maybe you could do a quick benchmarking?  a simple one, maybe run it on the project you're already working on using both `toString()` and the hashing approaches, although I don't think a couple extra milliseconds would make a big difference in the generation phase, I believe they'll matter if we ever could migrate to macros.

The unique fields in my opinion are the following
```
  int get identityHash =>
      type.identity.hashCode ^
      typeImpl.identity.hashCode ^
      injectableType.hashCode ^
      instanceName.hashCode ^
      orderPosition.hashCode ^
      scope.hashCode ^
      const ListEquality().hash(dependencies) ^
      const ListEquality().hash(dependsOn) ^
      const ListEquality().hash(environments);
```
I believe you can just copy and paste the above code over and run some tests.

**Comment by saschaernst** [comment]
It does not need to be late, does it?

**Comment by Milad-Akarie** [comment]
It kinda does,its accessing class members

**Comment by saschaernst** [comment]
But the value is set at that moment, not late(r). Anyways, I'd really love to see this improvements implemented, as it would increase the usability of injectable for bigger teams immensley.

Thanks to both of you for your work here!

**Comment by Adam-Langley** [comment]
Hi @Milad-Akarie could you have another crack at what you'd like it to be? This is the error as a late.

`Can't have a late final field in a class with a generative const constructor.
Try removing the 'late' modifier, or don't declare 'const' constructors.`

In the meantime, I'll test the logic still works with it as a getter (throwing perf under the bus).

**Comment by Milad-Akarie** [comment]
Hey @Adam-Langley  ya I guess it safe to remove the const keyword as `DependencyConfig` almost can never be a const instance.

**Comment by Adam-Langley** [comment]
@Milad-Akarie Thanks, will do. Can you also please direct me on what to look for in the code_builder which outputs the type aliases (_i1, _i2 etc) - so I can swap it for the identityHash?
Thanks,

**Comment by Milad-Akarie** [comment]
@Adam-Langley you'd need to implement a custom Allocator, I think a good starting point is auto_route's deferred allocator
https://github.com/Milad-Akarie/auto_route_library/blob/master/auto_route_generator/lib/src/code_builder/deferred_pages_allocator.dart

**Comment by Adam-Langley** [comment]
Hi @Milad-Akarie 
Ok, thats a lot more involved than the small, non-invasive change that this PR set out to be. 

Given this new information, I feel we should split this into 2 issues, one for simply fixing the regen churn, and the other for changing generated aliasing.
I originally felt they were very distinct issues, however I was hoping changing the aliasing method would be equally trivial (i.e. redirect to another member of DependencyConfig.

I have updated my commit.
Results: Churn eliminated (dependency ordering is now stable). No measurable impact to performance.

How do you feel about my suggestion to split?

**Comment by Milad-Akarie** [comment]
@Adam-Langley Thank you for your efforts, the fix has been published. 
obviously, I like the idea of splitting the two PRs

**Comment by cogivn** [comment]
@Milad-Akarie, @adam-langley-minrisk The sort function is missing this case:

```dart
test(
        'Sorting with environments in mind, should sort as [D,B{prd},C,B{dev}},A{dev}]',
            () {
          final deps = [
            DependencyConfig.factory('A', deps: ['B'], envs: ['dev', 'prod']),
            DependencyConfig.factory('B', envs: ['prod']),
            DependencyConfig.factory('B', envs: ['dev'], deps: ['C']),
            DependencyConfig.factory('C', deps: ['D']),
            DependencyConfig.factory('D'),
          ];
          final expectedResult = [
            DependencyConfig.factory('D'),
            DependencyConfig.factory('B', envs: ['prod']),
            DependencyConfig.factory('C', deps: ['D']),
            DependencyConfig.factory('B', envs: ['dev'], deps: ['C']),
            DependencyConfig.factory('A', deps: ['B'], envs: ['dev', 'prod']),
          ];
          expect(sortDependencies(deps).toList(), expectedResult);
        });
```

**Comment by Milad-Akarie** [comment]
@cogivn I believe this has to do with sort by dependents method, I'll check it out when I can

**Comment by cogivn** [comment]
> @cogivn I believe this has to do with sort by dependents method, I'll check it out when I can

@Milad-Akarie I already run the above case with master branch and the sort method return: `(D, C/(D), B, A/(B), B/(C))`

**Pull request merged**
