### PR TITLE
Set version constraints for analyzer to '>=4.6.0 <6.0.0'

### PR DESCRIPTION
**Pull request by amondnet**

### CODE REVIEW

**Comment by MuhammedKpln** [comment]
Hope it gets merged as fast as possible!

**Comment by dJani97** [comment]
Until this PR is merged, you can use the updated version like so:
```yaml
injectable_generator:
  git:
    url: https://github.com/amondnet/injectable.git
    path: injectable_generator
```

**Comment by sachebotarev** [comment]
@Milad-Akarie Please pay attention to this PR we look forward to

**Comment by Milad-Akarie** [comment]
Thank you for your efforts.

**Pull request merged**
